config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :links
  post 'url', to: 'links#generate_short_url'
  get 'top', to: 'links#top'
  get ':in_url' => 'links#go'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  validates :out_url, :http_status, presence: true
  validates :in_url, uniqueness: true
  validates :out_url, url: { schemes: ['https', 'http'] }

  after_create :scrap, :generate_short_url

  def scrap
    ScrapJob.perform_later self
  end

  def generate_short_url
    self.in_url = id.to_s(36)
    logger.debug 'link: ' + inspect
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def go
    @link = Link.find_by!(in_url: params[:in_url])
    @link.counter += 1 # increse counter
    @link.save
    redirect_to @link.out_url, status: @link.http_status
  rescue ActiveRecord::RecordNotFound
    render json: @link.errors, status: :unprocessable_entity
  end

  def top
    @links = Link.order(counter: :desc).limit(100)
    render json: @links, status: :ok
  end

  def generate_short_url
    # generate shorter url
    @link = Link.new(out_url: params[:url], counter: 1)
    if @link.save
      render json: short_url(params[:url]), status: :ok
    else
      render json: @link.errors, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :in_url %>
    <%= form.text_field :in_url %>
  </div>

  <div class="field">
    <%= form.label :out_url %>
    <%= form.text_area :out_url %>
  </div>

  <div class="field">
    <%= form.label :http_status %>
    <%= form.number_field :http_status %>
  </div>

  <div class="field">
    <%= form.label :counter %>
    <%= form.number_field :counter %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>In url</th>
      <th>Out url</th>
      <th>Http status</th>
      <th>Counter</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.in_url %></td>
        <td><%= link.out_url %></td>
        <td><%= link.http_status %></td>
        <td><%= link.counter %></td>
        <td><%= link.title %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>In url:</strong>
  <%= @link.in_url %>
</p>

<p>
  <strong>Out url:</strong>
  <%= @link.out_url %>
</p>

<p>
  <strong>Http status:</strong>
  <%= @link.http_status %>
</p>

<p>
  <strong>Counter:</strong>
  <%= @link.counter %>
</p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>